apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/bruno-sf/argocd-app-config.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true  # Not default behavior, should create the namespace in the dest cluster

    automated:
      selfHeal: true        # By default will not triggers automated sync, polling git rep every 3m, for faster syncs use a git webook to notify argo
      prune: true           # By default automatic sync will not delete resources
